### PR TITLE
Rewire AddressIndicator to use spinner-based selector

### PR DESCRIPTION
**Pull request by ethanfrey**
This is a minor fix-up.
I'd be glad for feedback if this is the proper approach to rewiring.

### CODE REVIEW

**Comment by ethanfrey** [comment]
@rudi-cilibrasi I agree.
But isn't that part in `bcp-redux`?
And we can just change where `addressSelectorForIdentitySpinner` gets the spinner info...
I mean, maybe we rename to `addressSelectorForMicroscopeLocation`...

**Comment by ethanfrey** [comment]
What is the approach for parallel prs?

**Comment by rudi-cilibrasi** [comment]
on parallel prs; best practice is to get both green buttons visible at once and then hit each in rapid succession before misguided colleagues accidentally sabotage squad goals. as for `addressSele...` name it should not start with `address` but `transient` in current hierarchical naming convention and it should have `Selector` at end...

**Comment by Isabello** [comment]
Closing this PR as we no longer have spinners in, we should use telescope instead.

**Pull request closed without merging**
